### ISSUE TITLE
Remove "or any later version" from all licences

### ISSUE THREAD

**Issue by brettsheffield** [librestack/librecast#39]
I like the GPL and strong copyleft licenses, but the FSF have shown they are not responsible stewards with their recent reappointment of RMS.  We can still use the existing published licenses, but we need to cut the cord with FSF by removing "or any later version" from our licenses which effectively gives that organisation control over the licensing of our project.

**Comment by onepict** [comment]
Do we need to specify a proxy as well? Like NLNet or conservancy in the license? 

Just saw a tweet on twitter about that. 

⁣Sent from BlueMail ​


-------- Original Message --------
From: Brett Sheffield ***@***.***>
Sent: Mon Apr 12 18:30:49 GMT+02:00 2021
To: librestack/librecast ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [librestack/librecast] Remove "or any later version" from all licences (#39)

I like the GPL and strong copyleft licenses, but the FSF have shown they are not responsible stewards with their recent reappointment of RMS.  We can still use the existing published licenses, but we need to cut the cord with FSF by removing "or any later version" from our licenses which effectively gives that organisation control over the licensing of our project.

-- 
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/librestack/librecast/issues/39

**Comment by onepict** [comment]
Discussion last night:
At the moment no need to assign proxy.  Removing the Or Later will do for now.

**Comment by onepict** [comment]
Started on Librecast code.  Still TODO: Check test code.
Await review on existing changes before starting on tests as updates to test code are still ongoing.
